# Working with matrices: a very brief summary

To work with matrices (arrays) you should import the `numpy` package.

In [42]:
import numpy

The code below generates a random 10 row, 3 column array containing random numbers from 1 to 10. This array will be used in the examples below.

In [43]:
my_array = numpy.random.randint(1,10, size=(10, 3))
my_array

array([[6, 7, 7],
       [8, 5, 2],
       [6, 6, 5],
       [2, 6, 4],
       [8, 8, 2],
       [8, 6, 4],
       [7, 5, 7],
       [9, 8, 6],
       [2, 6, 3],
       [2, 4, 8]])

## Slicing: getting parts of arrays

The syntax for getting parts of an array is the following:

`array[row_indices:column_indices]`

Remember that the indices for both rows and columns start at 0. If you want to select a complete row or column you can put `:` for that dimension.

**Examples**

In [44]:
# Getting the first row. the
row = my_array[0, :]
print('first row:', row)

# Getting the 4th row. the
row = my_array[3, :]
print('fourth row:', row)

# Getting the 1st column. the
row = my_array[: ,0]
print('first column:', row)

first row: [6 7 7]
fourth row: [2 6 4]
first column: [6 8 6 2 8 8 7 9 2 2]


## Operations

Using `numpy`, you can perform several operation on arrays. The

In [45]:
result = numpy.max(my_array)
result = numpy.min(my_array)
result = numpy.mean(my_array)

# Getting the indices of the max and the minimum values can come in handy

result = numpy.argmin(my_array)
result = numpy.argmax(my_array)

## Calculating with matrices

You can multiply, divide, add and subtract with matrices

In [46]:
(((my_array * 7) + 12.6) - 75) / 1334

array([[-0.01529235, -0.01004498, -0.01004498],
       [-0.0047976 , -0.02053973, -0.03628186],
       [-0.01529235, -0.01529235, -0.02053973],
       [-0.03628186, -0.01529235, -0.02578711],
       [-0.0047976 , -0.0047976 , -0.03628186],
       [-0.0047976 , -0.01529235, -0.02578711],
       [-0.01004498, -0.02053973, -0.01004498],
       [ 0.00044978, -0.0047976 , -0.01529235],
       [-0.03628186, -0.01529235, -0.03103448],
       [-0.03628186, -0.02578711, -0.0047976 ]])

You can multiply, divide, add and subtract two matrices, provided they have the same size.

In [47]:
my_array[:,0] + my_array[:,1] +  my_array[:,2]


array([20, 15, 17, 12, 18, 18, 19, 23, 11, 14])